nombre = input("Ingrese su nombre: ")
apellido = input("Ingrese su apellido: ")
asignatura = input("Ingrese asignatura: ")
sede = input("ingrese su sede de INACAP: ")
print(nombre, apellido, asignatura, sede)